//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disney.iDash.iDashController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disney.iDash.iDashController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE 
        ///	FROM DSIALOK
        ///WHERE 
        ///	IACLS=&lt;IACLS&gt;
        ///	AND IAVEN=&lt;IAVEN&gt;
        ///	AND IASTY=&lt;IASTY&gt;
        ///	AND IACLR=&lt;IACLR&gt;
        ///	AND IASIZ=&lt;IASIZ&gt;
        ///	AND IASUSER=&apos;&lt;IAUSER&gt;&apos;.
        /// </summary>
        internal static string SQL_DSIALOK_Delete {
            get {
                return ResourceManager.GetString("SQL_DSIALOK_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM DSIALOK ORDER BY IACLS, IAVEN, IASTY, IACLR, IASIZ.
        /// </summary>
        internal static string SQL_DSIALOK_Select {
            get {
                return ResourceManager.GetString("SQL_DSIALOK_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM DSSRLCK 
        ///WHERE.
        /// </summary>
        internal static string SQL_DSSRLCK_Delete {
            get {
                return ResourceManager.GetString("SQL_DSSRLCK_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM DSSRLCK ORDER BY LODEPT, LOCLS, LOVEN, LOSTY.
        /// </summary>
        internal static string SQL_DSSRLCK_Select {
            get {
                return ResourceManager.GetString("SQL_DSSRLCK_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM DSSRSMSG WHERE MGKEY=&lt;MGKEY&gt;.
        /// </summary>
        internal static string SQL_DSSRSMSG_Delete {
            get {
                return ResourceManager.GetString("SQL_DSSRSMSG_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///	DSSRSMSG
        ///		(MGKEY, MGSYSN, MGUSER, MGSTRT, MGENDT, MGMON, MGTUE, MGWED, MGTHU, MGFRI, MGSAT, MGSUN, MGMSG, MGSTS, MGTRM)
        ///	VALUES
        ///		(&lt;MGKEY&gt;, &apos;&lt;MGSYSN&gt;&apos;, &apos;&lt;MGUSER&gt;&apos;, &lt;MGSTRT&gt;, &lt;MGENDT&gt;, &lt;MGMON&gt;, &lt;MGTUE&gt;, &lt;MGWED&gt;, &lt;MGTHU&gt;, &lt;MGFRI&gt;, &lt;MGSAT&gt;, &lt;MGSUN&gt;, &apos;&lt;MGMSG&gt;&apos;, &lt;MGSTS&gt;, &lt;MGTRM&gt;).
        /// </summary>
        internal static string SQL_DSSRSMSG_Insert {
            get {
                return ResourceManager.GetString("SQL_DSSRSMSG_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM DSSRSMSG ORDER BY MGKEY.
        /// </summary>
        internal static string SQL_DSSRSMSG_Select {
            get {
                return ResourceManager.GetString("SQL_DSSRSMSG_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 			
        ///	DSSRSMSG		
        ///SET			
        ///	MGSYSN	=	&apos;&lt;MGSYSN&gt;&apos;,
        ///	MGUSER  =   &apos;&lt;MGUSER&gt;&apos;, 
        ///	MGSTRT	=	&lt;MGSTRT&gt;,
        ///	MGENDT	=	&lt;MGENDT&gt;,
        ///	MGMON	=	&lt;MGMON&gt;,
        ///	MGTUE	=	&lt;MGTUE&gt;,
        ///	MGWED	=	&lt;MGWED&gt;,
        ///	MGTHU	=	&lt;MGTHU&gt;,
        ///	MGFRI	=	&lt;MGFRI&gt;,
        ///	MGSAT	=	&lt;MGSAT&gt;,
        ///	MGSUN	=	&lt;MGSUN&gt;,
        ///	MGMSG	=	&apos;&lt;MGMSG&gt;&apos;,
        ///	MGSTS	=	&lt;MGSTS&gt;,
        ///	MGTRM	=	&lt;MGTRM&gt;
        ///			
        ///WHERE			
        ///	MGKEY	=	&lt;MGKEY&gt;
        ///.
        /// </summary>
        internal static string SQL_DSSRSMSG_Update {
            get {
                return ResourceManager.GetString("SQL_DSSRSMSG_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM DSSRUML ORDER BY UMSMNA, UMSMAS.
        /// </summary>
        internal static string SQL_DSSRUML_Select {
            get {
                return ResourceManager.GetString("SQL_DSSRUML_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///	DSSRUML
        ///SET
        ///	UMSFLG = &apos;&lt;UMSFLG&gt;&apos;,
        ///	UMSUID = &apos;&lt;UMSUID&gt;&apos;,
        ///	UMSUDT = &apos;&lt;UMSUDT&gt;&apos;
        ///WHERE
        ///	UMSMNA = &apos;&lt;UMSMNA&gt;&apos;
        ///	AND UMSMAS = &apos;&lt;UMSMAS&gt;&apos;.
        /// </summary>
        internal static string SQL_DSSRUML_Update {
            get {
                return ResourceManager.GetString("SQL_DSSRUML_Update", resourceCulture);
            }
        }
    }
}
